### ISSUE TITLE
SearchBar shenanigans

### ISSUE THREAD

**Issue by matildepark** [johnhyde/astrolabe#2]
Was playing around with solutions here but not sure yet — basically on first load if you type a number then it gets overwritten by the converted patp, but then subsequent entries work fine without conversion. 

This is because the route doesn't change anymore, so the params don't change, and subsequent searches also don't operate if you delete the entire search field.

If we use a fallback old date instead of falling back to `null` or `~` values in ShipViewPage, eg.

```ts
  $: paramChanged = params.patp ? Date.now() : Date.parse('Jan 1 2000');
  $: analysisPatpChanged = analysis.patp ? Date.now() : Date.parse('Jan 1 2000');
```

Then our search bar is more active, consistently works, but um, more consistently overwrites incoming digits with their patp equivalents? So not a solution, but I think it unmasks the problem. 

I think the search should probably be uncontrolled and use an `onChange` handler as we type instead of setting the value directly from params, letting the search results change as we type but not manipulating the search buffer itself.

**Comment by johnhyde** [comment]
Thanks, this is fixed in the latest patch (0.0.2). I decided to add a queryParam, `search`, when the search bar is different from the actual `@p`.
